// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProSkills.Models;

#nullable disable

namespace ProSkills.Migrations
{
    [DbContext(typeof(ITIContext))]
    [Migration("20240519233545_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProSkills.Models.AdminPanel.InstructorManger.instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciallization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("instructor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Bio for Instructor 1",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor1@example.com",
                            IsDeleted = false,
                            Name = "Instructor 1",
                            Password = "password1"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Bio for Instructor 2",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor2@example.com",
                            IsDeleted = false,
                            Name = "Instructor 2",
                            Password = "password2"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Bio for Instructor 3",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor3@example.com",
                            IsDeleted = false,
                            Name = "Instructor 3",
                            Password = "password3"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Bio for Instructor 4",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor4@example.com",
                            IsDeleted = false,
                            Name = "Instructor 4",
                            Password = "password4"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Bio for Instructor 5",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor5@example.com",
                            IsDeleted = false,
                            Name = "Instructor 5",
                            Password = "password5"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Bio for Instructor 6",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor6@example.com",
                            IsDeleted = false,
                            Name = "Instructor 6",
                            Password = "password6"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Bio for Instructor 7",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor7@example.com",
                            IsDeleted = false,
                            Name = "Instructor 7",
                            Password = "password7"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Bio for Instructor 8",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor8@example.com",
                            IsDeleted = false,
                            Name = "Instructor 8",
                            Password = "password8"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Bio for Instructor 9",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor9@example.com",
                            IsDeleted = false,
                            Name = "Instructor 9",
                            Password = "password9"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Bio for Instructor 10",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor10@example.com",
                            IsDeleted = false,
                            Name = "Instructor 10",
                            Password = "password10"
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Bio for Instructor 11",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor11@example.com",
                            IsDeleted = false,
                            Name = "Instructor 11",
                            Password = "password11"
                        },
                        new
                        {
                            Id = 12,
                            Bio = "Bio for Instructor 12",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor12@example.com",
                            IsDeleted = false,
                            Name = "Instructor 12",
                            Password = "password12"
                        },
                        new
                        {
                            Id = 13,
                            Bio = "Bio for Instructor 13",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor13@example.com",
                            IsDeleted = false,
                            Name = "Instructor 13",
                            Password = "password13"
                        },
                        new
                        {
                            Id = 14,
                            Bio = "Bio for Instructor 14",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor14@example.com",
                            IsDeleted = false,
                            Name = "Instructor 14",
                            Password = "password14"
                        },
                        new
                        {
                            Id = 15,
                            Bio = "Bio for Instructor 15",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor15@example.com",
                            IsDeleted = false,
                            Name = "Instructor 15",
                            Password = "password15"
                        },
                        new
                        {
                            Id = 16,
                            Bio = "Bio for Instructor 16",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor16@example.com",
                            IsDeleted = false,
                            Name = "Instructor 16",
                            Password = "password16"
                        },
                        new
                        {
                            Id = 17,
                            Bio = "Bio for Instructor 17",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor17@example.com",
                            IsDeleted = false,
                            Name = "Instructor 17",
                            Password = "password17"
                        },
                        new
                        {
                            Id = 18,
                            Bio = "Bio for Instructor 18",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor18@example.com",
                            IsDeleted = false,
                            Name = "Instructor 18",
                            Password = "password18"
                        },
                        new
                        {
                            Id = 19,
                            Bio = "Bio for Instructor 19",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor19@example.com",
                            IsDeleted = false,
                            Name = "Instructor 19",
                            Password = "password19"
                        },
                        new
                        {
                            Id = 20,
                            Bio = "Bio for Instructor 20",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor20@example.com",
                            IsDeleted = false,
                            Name = "Instructor 20",
                            Password = "password20"
                        },
                        new
                        {
                            Id = 21,
                            Bio = "Bio for Instructor 21",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor21@example.com",
                            IsDeleted = false,
                            Name = "Instructor 21",
                            Password = "password21"
                        },
                        new
                        {
                            Id = 22,
                            Bio = "Bio for Instructor 22",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor22@example.com",
                            IsDeleted = false,
                            Name = "Instructor 22",
                            Password = "password22"
                        },
                        new
                        {
                            Id = 23,
                            Bio = "Bio for Instructor 23",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor23@example.com",
                            IsDeleted = false,
                            Name = "Instructor 23",
                            Password = "password23"
                        },
                        new
                        {
                            Id = 24,
                            Bio = "Bio for Instructor 24",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor24@example.com",
                            IsDeleted = false,
                            Name = "Instructor 24",
                            Password = "password24"
                        },
                        new
                        {
                            Id = 25,
                            Bio = "Bio for Instructor 25",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor25@example.com",
                            IsDeleted = false,
                            Name = "Instructor 25",
                            Password = "password25"
                        },
                        new
                        {
                            Id = 26,
                            Bio = "Bio for Instructor 26",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor26@example.com",
                            IsDeleted = false,
                            Name = "Instructor 26",
                            Password = "password26"
                        },
                        new
                        {
                            Id = 27,
                            Bio = "Bio for Instructor 27",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor27@example.com",
                            IsDeleted = false,
                            Name = "Instructor 27",
                            Password = "password27"
                        },
                        new
                        {
                            Id = 28,
                            Bio = "Bio for Instructor 28",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor28@example.com",
                            IsDeleted = false,
                            Name = "Instructor 28",
                            Password = "password28"
                        },
                        new
                        {
                            Id = 29,
                            Bio = "Bio for Instructor 29",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor29@example.com",
                            IsDeleted = false,
                            Name = "Instructor 29",
                            Password = "password29"
                        },
                        new
                        {
                            Id = 30,
                            Bio = "Bio for Instructor 30",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "instructor30@example.com",
                            IsDeleted = false,
                            Name = "Instructor 30",
                            Password = "password30"
                        });
                });

            modelBuilder.Entity("ProSkills.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "Revit"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "Sap"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "Etabs"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "Forge"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "primavera"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "wpf"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "Windows Form"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "NavisWorks"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Image = "",
                            IsDeleted = false,
                            Name = "Graphics"
                        });
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Hours")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfAssessment")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfLessons")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfStudents")
                        .HasColumnType("int");

                    b.Property<string>("RedeemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalFilesSize")
                        .HasColumnType("float");

                    b.Property<int>("instructorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("instructorId");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course provides an introduction to programming concepts and techniques.",
                            EndAt = new DateTime(2024, 6, 19, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6761),
                            Hours = 40,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Introduction to Programming",
                            NumberOfAssessment = 5,
                            NumberOfLessons = 20,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 27, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6757),
                            TotalFilesSize = 10.5,
                            instructorId = 12
                        },
                        new
                        {
                            Id = 2,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the basics of web development including HTML, CSS, and JavaScript.",
                            EndAt = new DateTime(2024, 7, 4, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6809),
                            Hours = 60,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Web Development Fundamentals",
                            NumberOfAssessment = 7,
                            NumberOfLessons = 25,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 6, 3, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6807),
                            TotalFilesSize = 15.199999999999999,
                            instructorId = 13
                        },
                        new
                        {
                            Id = 3,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers fundamental data structures and algorithms.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6820),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Data Structures and Algorithms",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 25, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6818),
                            TotalFilesSize = 11.699999999999999,
                            instructorId = 4
                        },
                        new
                        {
                            Id = 4,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course provides an introduction to machine learning concepts and techniques.",
                            EndAt = new DateTime(2024, 7, 19, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6840),
                            Hours = 55,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Machine Learning Basics",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 23,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 30, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6838),
                            TotalFilesSize = 13.5,
                            instructorId = 12
                        },
                        new
                        {
                            Id = 5,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the design and management of relational databases.",
                            EndAt = new DateTime(2024, 6, 29, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6850),
                            Hours = 50,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Database Design and Management",
                            NumberOfAssessment = 7,
                            NumberOfLessons = 25,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 5, 27, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6848),
                            TotalFilesSize = 14.1,
                            instructorId = 15
                        },
                        new
                        {
                            Id = 6,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course provides an overview of cybersecurity concepts and principles.",
                            EndAt = new DateTime(2024, 7, 9, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6860),
                            Hours = 55,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Cybersecurity Fundamentals",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 24,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 6, 1, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6859),
                            TotalFilesSize = 12.300000000000001,
                            instructorId = 8
                        },
                        new
                        {
                            Id = 7,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers fundamental concepts and techniques in artificial intelligence.",
                            EndAt = new DateTime(2024, 7, 14, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6870),
                            Hours = 50,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Artificial Intelligence Basics",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 23,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 28, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6868),
                            TotalFilesSize = 12.800000000000001,
                            instructorId = 11
                        },
                        new
                        {
                            Id = 8,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers software engineering principles and best practices.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6884),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Software Engineering Principles",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 5, 26, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6883),
                            TotalFilesSize = 13.199999999999999,
                            instructorId = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the basics of Python programming language.",
                            EndAt = new DateTime(2024, 6, 29, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6895),
                            Hours = 40,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Python Programming Basics",
                            NumberOfAssessment = 5,
                            NumberOfLessons = 20,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 29, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6893),
                            TotalFilesSize = 10.800000000000001,
                            instructorId = 10
                        },
                        new
                        {
                            Id = 10,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers data analysis techniques using Python programming language.",
                            EndAt = new DateTime(2024, 7, 4, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6904),
                            Hours = 50,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Data Analysis with Python",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 31, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6903),
                            TotalFilesSize = 12.199999999999999,
                            instructorId = 7
                        },
                        new
                        {
                            Id = 11,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the fundamentals of Java programming language.",
                            EndAt = new DateTime(2024, 7, 9, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6914),
                            Hours = 55,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Java Programming Fundamentals",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 24,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 6, 2, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6912),
                            TotalFilesSize = 13.5,
                            instructorId = 7
                        },
                        new
                        {
                            Id = 12,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers essential concepts in computer networks.",
                            EndAt = new DateTime(2024, 6, 29, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6926),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Computer Networks Essentials",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 5, 30, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6925),
                            TotalFilesSize = 13.1,
                            instructorId = 14
                        },
                        new
                        {
                            Id = 13,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course provides an introduction to the Linux operating system.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6936),
                            Hours = 40,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Introduction to Linux",
                            NumberOfAssessment = 5,
                            NumberOfLessons = 20,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 28, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6935),
                            TotalFilesSize = 10.6,
                            instructorId = 6
                        },
                        new
                        {
                            Id = 14,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the basics of mobile app development.",
                            EndAt = new DateTime(2024, 6, 19, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6946),
                            Hours = 35,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Mobile App Development Basics",
                            NumberOfAssessment = 5,
                            NumberOfLessons = 18,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 27, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6944),
                            TotalFilesSize = 11.199999999999999,
                            instructorId = 12
                        },
                        new
                        {
                            Id = 15,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers frontend web development technologies and frameworks.",
                            EndAt = new DateTime(2024, 7, 4, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6955),
                            Hours = 60,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Frontend Web Development",
                            NumberOfAssessment = 7,
                            NumberOfLessons = 25,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 6, 3, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6954),
                            TotalFilesSize = 15.800000000000001,
                            instructorId = 4
                        },
                        new
                        {
                            Id = 16,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course provides an introduction to cloud computing concepts and services.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6967),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Cloud Computing Fundamentals",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 25, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6966),
                            TotalFilesSize = 12.5,
                            instructorId = 13
                        },
                        new
                        {
                            Id = 17,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the fundamentals of React.js library for building user interfaces.",
                            EndAt = new DateTime(2024, 7, 9, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6977),
                            Hours = 55,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "React.js Fundamentals",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 24,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 6, 1, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6975),
                            TotalFilesSize = 13.800000000000001,
                            instructorId = 4
                        },
                        new
                        {
                            Id = 18,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers server-side development with Node.js runtime environment.",
                            EndAt = new DateTime(2024, 7, 14, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6986),
                            Hours = 50,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Node.js Development",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 23,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 28, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6985),
                            TotalFilesSize = 12.300000000000001,
                            instructorId = 4
                        },
                        new
                        {
                            Id = 19,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers database concepts and technologies for developers.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6996),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Databases for Developers",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 26, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(6994),
                            TotalFilesSize = 13.1,
                            instructorId = 2
                        },
                        new
                        {
                            Id = 20,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course provides an introduction to deep learning concepts and techniques.",
                            EndAt = new DateTime(2024, 6, 29, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7009),
                            Hours = 40,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Deep Learning Fundamentals",
                            NumberOfAssessment = 5,
                            NumberOfLessons = 20,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 5, 29, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7007),
                            TotalFilesSize = 11.800000000000001,
                            instructorId = 11
                        },
                        new
                        {
                            Id = 21,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers essential cybersecurity concepts and practices.",
                            EndAt = new DateTime(2024, 7, 4, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7019),
                            Hours = 50,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Cybersecurity Essentials",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 31, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7018),
                            TotalFilesSize = 12.5,
                            instructorId = 5
                        },
                        new
                        {
                            Id = 22,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the basics of Ruby programming language.",
                            EndAt = new DateTime(2024, 7, 9, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7029),
                            Hours = 55,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Ruby Programming Basics",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 24,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 6, 2, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7028),
                            TotalFilesSize = 13.199999999999999,
                            instructorId = 6
                        },
                        new
                        {
                            Id = 23,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers fundamental concepts in computer architecture.",
                            EndAt = new DateTime(2024, 6, 29, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7040),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Computer Architecture Fundamentals",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 5, 30, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7039),
                            TotalFilesSize = 13.6,
                            instructorId = 8
                        },
                        new
                        {
                            Id = 24,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the basics of JavaScript programming language.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7081),
                            Hours = 40,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "JavaScript Programming Basics",
                            NumberOfAssessment = 5,
                            NumberOfLessons = 20,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 28, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7078),
                            TotalFilesSize = 10.9,
                            instructorId = 14
                        },
                        new
                        {
                            Id = 25,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers fundamental concepts and techniques in software testing.",
                            EndAt = new DateTime(2024, 6, 19, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7091),
                            Hours = 35,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Software Testing Fundamentals",
                            NumberOfAssessment = 5,
                            NumberOfLessons = 18,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 27, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7090),
                            TotalFilesSize = 11.4,
                            instructorId = 5
                        },
                        new
                        {
                            Id = 26,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the fundamentals of Angular framework for building web applications.",
                            EndAt = new DateTime(2024, 7, 4, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7101),
                            Hours = 60,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Angular Framework Fundamentals",
                            NumberOfAssessment = 7,
                            NumberOfLessons = 25,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 6, 3, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7099),
                            TotalFilesSize = 15.199999999999999,
                            instructorId = 4
                        },
                        new
                        {
                            Id = 27,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the basics of iOS app development using Swift programming language.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7112),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "iOS App Development Basics",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 25, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7110),
                            TotalFilesSize = 13.699999999999999,
                            instructorId = 1
                        },
                        new
                        {
                            Id = 28,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers server-side web development with ASP.NET Core framework.",
                            EndAt = new DateTime(2024, 7, 9, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7128),
                            Hours = 55,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "ASP.NET Core Development",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 24,
                            NumberOfStudents = 30,
                            StartAt = new DateTime(2024, 6, 1, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7126),
                            TotalFilesSize = 14.300000000000001,
                            instructorId = 9
                        },
                        new
                        {
                            Id = 29,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the fundamentals of C# programming language.",
                            EndAt = new DateTime(2024, 7, 14, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7139),
                            Hours = 50,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "C# Programming Fundamentals",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 23,
                            NumberOfStudents = 20,
                            StartAt = new DateTime(2024, 5, 28, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7137),
                            TotalFilesSize = 12.6,
                            instructorId = 11
                        },
                        new
                        {
                            Id = 30,
                            CourseImagePath = "path/to/trainee/image.jpg",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Description = "This course covers the fundamentals of game development using Unity game engine.",
                            EndAt = new DateTime(2024, 6, 24, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7150),
                            Hours = 45,
                            IsDeleted = false,
                            Location = "Online",
                            Name = "Unity Game Development Fundamentals",
                            NumberOfAssessment = 6,
                            NumberOfLessons = 22,
                            NumberOfStudents = 25,
                            StartAt = new DateTime(2024, 5, 26, 2, 35, 45, 425, DateTimeKind.Local).AddTicks(7148),
                            TotalFilesSize = 13.9,
                            instructorId = 14
                        });
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.CourseTrainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Result")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CourseTrainee");
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfAssesments")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLessons")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTrainees")
                        .HasColumnType("int");

                    b.Property<double>("TotlaFileSize")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Package");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Hours = 10,
                            Image = "image1.jpg",
                            IsDeleted = false,
                            Name = "free",
                            NumberOfAssesments = 5,
                            NumberOfLessons = 15,
                            NumberOfTrainees = 20,
                            TotlaFileSize = 1024.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Hours = 10,
                            Image = "image2.jpg",
                            IsDeleted = false,
                            Name = "Premium",
                            NumberOfAssesments = 5,
                            NumberOfLessons = 15,
                            NumberOfTrainees = 40,
                            TotlaFileSize = 1024.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Hours = 10,
                            Image = "image3.jpg",
                            IsDeleted = false,
                            Name = "Advanced",
                            NumberOfAssesments = 5,
                            NumberOfLessons = 15,
                            NumberOfTrainees = 40,
                            TotlaFileSize = 1024.0
                        });
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.RedeemCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PackageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isAvalible")
                        .HasColumnType("bit");

                    b.Property<int>("packageid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RedeemCode");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Code = "gamal",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            IsDeleted = false,
                            PackageName = "premium",
                            isAvalible = true,
                            packageid = 1
                        });
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Steps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Bio for Trainee 1",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee1@example.com",
                            IsDeleted = false,
                            Name = "Trainee 1",
                            Password = "password1"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Bio for Trainee 2",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee2@example.com",
                            IsDeleted = false,
                            Name = "Trainee 2",
                            Password = "password2"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Bio for Trainee 3",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee3@example.com",
                            IsDeleted = false,
                            Name = "Trainee 3",
                            Password = "password3"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Bio for Trainee 4",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee4@example.com",
                            IsDeleted = false,
                            Name = "Trainee 4",
                            Password = "password4"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Bio for Trainee 5",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee5@example.com",
                            IsDeleted = false,
                            Name = "Trainee 5",
                            Password = "password5"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Bio for Trainee 6",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee6@example.com",
                            IsDeleted = false,
                            Name = "Trainee 6",
                            Password = "password6"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Bio for Trainee 7",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee7@example.com",
                            IsDeleted = false,
                            Name = "Trainee 7",
                            Password = "password7"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Bio for Trainee 8",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee8@example.com",
                            IsDeleted = false,
                            Name = "Trainee 8",
                            Password = "password8"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Bio for Trainee 9",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee9@example.com",
                            IsDeleted = false,
                            Name = "Trainee 9",
                            Password = "password9"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Bio for Trainee 10",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee10@example.com",
                            IsDeleted = false,
                            Name = "Trainee 10",
                            Password = "password10"
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Bio for Trainee 11",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee11@example.com",
                            IsDeleted = false,
                            Name = "Trainee 11",
                            Password = "password11"
                        },
                        new
                        {
                            Id = 12,
                            Bio = "Bio for Trainee 12",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee12@example.com",
                            IsDeleted = false,
                            Name = "Trainee 12",
                            Password = "password12"
                        },
                        new
                        {
                            Id = 13,
                            Bio = "Bio for Trainee 13",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee13@example.com",
                            IsDeleted = false,
                            Name = "Trainee 13",
                            Password = "password13"
                        },
                        new
                        {
                            Id = 14,
                            Bio = "Bio for Trainee 14",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee14@example.com",
                            IsDeleted = false,
                            Name = "Trainee 14",
                            Password = "password14"
                        },
                        new
                        {
                            Id = 15,
                            Bio = "Bio for Trainee 15",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee15@example.com",
                            IsDeleted = false,
                            Name = "Trainee 15",
                            Password = "password15"
                        },
                        new
                        {
                            Id = 16,
                            Bio = "Bio for Trainee 16",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee16@example.com",
                            IsDeleted = false,
                            Name = "Trainee 16",
                            Password = "password16"
                        },
                        new
                        {
                            Id = 17,
                            Bio = "Bio for Trainee 17",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee17@example.com",
                            IsDeleted = false,
                            Name = "Trainee 17",
                            Password = "password17"
                        },
                        new
                        {
                            Id = 18,
                            Bio = "Bio for Trainee 18",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee18@example.com",
                            IsDeleted = false,
                            Name = "Trainee 18",
                            Password = "password18"
                        },
                        new
                        {
                            Id = 19,
                            Bio = "Bio for Trainee 19",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee19@example.com",
                            IsDeleted = false,
                            Name = "Trainee 19",
                            Password = "password19"
                        },
                        new
                        {
                            Id = 20,
                            Bio = "Bio for Trainee 20",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee20@example.com",
                            IsDeleted = false,
                            Name = "Trainee 20",
                            Password = "password20"
                        },
                        new
                        {
                            Id = 21,
                            Bio = "Bio for Trainee 21",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee21@example.com",
                            IsDeleted = false,
                            Name = "Trainee 21",
                            Password = "password21"
                        },
                        new
                        {
                            Id = 22,
                            Bio = "Bio for Trainee 22",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee22@example.com",
                            IsDeleted = false,
                            Name = "Trainee 22",
                            Password = "password22"
                        },
                        new
                        {
                            Id = 23,
                            Bio = "Bio for Trainee 23",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee23@example.com",
                            IsDeleted = false,
                            Name = "Trainee 23",
                            Password = "password23"
                        },
                        new
                        {
                            Id = 24,
                            Bio = "Bio for Trainee 24",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee24@example.com",
                            IsDeleted = false,
                            Name = "Trainee 24",
                            Password = "password24"
                        },
                        new
                        {
                            Id = 25,
                            Bio = "Bio for Trainee 25",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee25@example.com",
                            IsDeleted = false,
                            Name = "Trainee 25",
                            Password = "password25"
                        },
                        new
                        {
                            Id = 26,
                            Bio = "Bio for Trainee 26",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee26@example.com",
                            IsDeleted = false,
                            Name = "Trainee 26",
                            Password = "password26"
                        },
                        new
                        {
                            Id = 27,
                            Bio = "Bio for Trainee 27",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee27@example.com",
                            IsDeleted = false,
                            Name = "Trainee 27",
                            Password = "password27"
                        },
                        new
                        {
                            Id = 28,
                            Bio = "Bio for Trainee 28",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee28@example.com",
                            IsDeleted = false,
                            Name = "Trainee 28",
                            Password = "password28"
                        },
                        new
                        {
                            Id = 29,
                            Bio = "Bio for Trainee 29",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee29@example.com",
                            IsDeleted = false,
                            Name = "Trainee 29",
                            Password = "password29"
                        },
                        new
                        {
                            Id = 30,
                            Bio = "Bio for Trainee 30",
                            CreatedAt = "20/05/2024 2:35:45 am",
                            Email = "Trainee30@example.com",
                            IsDeleted = false,
                            Name = "Trainee 30",
                            Password = "password30"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProSkills.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProSkills.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProSkills.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProSkills.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Course", b =>
                {
                    b.HasOne("ProSkills.Models.AdminPanel.InstructorManger.instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("instructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.CourseTrainee", b =>
                {
                    b.HasOne("ProSkills.Models.ClientSide.Course", "Course")
                        .WithMany("Trainees")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProSkills.Models.ClientSide.Trainee", "Trainee")
                        .WithMany("Courses")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Steps", b =>
                {
                    b.HasOne("ProSkills.Models.ClientSide.Course", "Course")
                        .WithMany("steps")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Course", b =>
                {
                    b.Navigation("Trainees");

                    b.Navigation("steps");
                });

            modelBuilder.Entity("ProSkills.Models.ClientSide.Trainee", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
